# Audio Processing Settings
SPECTRUM_IMAGE_FILTER_SIZE = 30
CONSTELLATION_SHAPE = (128, 1025)

# Scoring Settings
SCORING_BIN_WIDTH = 0.5

# Target Zone Settings
TARGET_ZONE_WIDTH = 1.8
TARGET_ZONE_HEIGHT = 4000
TARGET_ZONE_TIME_OFFSET = 0.05

