# Audio Processing Settings
SPECTRUM_IMAGE_FILTER_SIZE = 57
CONSTELLATION_SHAPE = (128, 2049)

# Scoring Settings
SCORING_BIN_WIDTH = 0.5

# Target Zone Settings
TARGET_ZONE_WIDTH = 15
TARGET_ZONE_HEIGHT = 4000
TARGET_ZONE_TIME_OFFSET = 0.05

